# Generated by Django 5.1.2 on 2026-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='referral_paid',
            field=models.BooleanField(default=False),
        ),
    ]
